# Generated by Django 2.2.7 on 2019-12-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterusers', '0002_twitteruser_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_following', to='twitterusers.TwitterUser'),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='follwers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_followers', to='twitterusers.TwitterUser'),
        ),
    ]
