# Generated by Django 2.2.7 on 2019-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_author'),
        ('twitterusers', '0003_auto_20191206_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='tweets',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='tweets',
            field=models.ManyToManyField(to='tweets.Tweet'),
        ),
    ]
