# Generated by Django 2.2.7 on 2019-12-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterusers', '0004_auto_20191209_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='following',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(related_name='users_following', to='twitterusers.TwitterUser'),
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='follwers',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='follwers',
            field=models.ManyToManyField(related_name='users_followers', to='twitterusers.TwitterUser'),
        ),
    ]
